version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data